// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logdmvn_arma
double logdmvn_arma(const arma::vec& x, const arma::mat& Sigma);
RcppExport SEXP _CBKMR_logdmvn_arma(SEXP xSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(logdmvn_arma(x, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// logdmvn_arma_with_U
Rcpp::List logdmvn_arma_with_U(const arma::vec& x, const arma::mat& Sigma);
RcppExport SEXP _CBKMR_logdmvn_arma_with_U(SEXP xSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(logdmvn_arma_with_U(x, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// lCBpdf_bernoulli_no_X
double lCBpdf_bernoulli_no_X(const arma::vec& y, double beta0, Rcpp::RObject Ut);
RcppExport SEXP _CBKMR_lCBpdf_bernoulli_no_X(SEXP ySEXP, SEXP beta0SEXP, SEXP UtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type Ut(UtSEXP);
    rcpp_result_gen = Rcpp::wrap(lCBpdf_bernoulli_no_X(y, beta0, Ut));
    return rcpp_result_gen;
END_RCPP
}
// build_AD_rcpp
Rcpp::List build_AD_rcpp(const arma::mat& coords, const arma::imat& neighbor_matrix, double sigma2, double nugget_stabilizer);
RcppExport SEXP _CBKMR_build_AD_rcpp(SEXP coordsSEXP, SEXP neighbor_matrixSEXP, SEXP sigma2SEXP, SEXP nugget_stabilizerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type neighbor_matrix(neighbor_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type nugget_stabilizer(nugget_stabilizerSEXP);
    rcpp_result_gen = Rcpp::wrap(build_AD_rcpp(coords, neighbor_matrix, sigma2, nugget_stabilizer));
    return rcpp_result_gen;
END_RCPP
}
// rnngp_loglik_tauonly
double rnngp_loglik_tauonly(const arma::vec& x, const arma::mat& coords, const arma::rowvec& w, double tau, const arma::imat& neighbor_matrix, double nugget);
RcppExport SEXP _CBKMR_rnngp_loglik_tauonly(SEXP xSEXP, SEXP coordsSEXP, SEXP wSEXP, SEXP tauSEXP, SEXP neighbor_matrixSEXP, SEXP nuggetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type neighbor_matrix(neighbor_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type nugget(nuggetSEXP);
    rcpp_result_gen = Rcpp::wrap(rnngp_loglik_tauonly(x, coords, w, tau, neighbor_matrix, nugget));
    return rcpp_result_gen;
END_RCPP
}
// rnngp_loglik_tauonly_use_AD
Rcpp::List rnngp_loglik_tauonly_use_AD(const arma::vec& x, const arma::mat& coords, const arma::rowvec& w, double tau, const arma::imat& neighbor_matrix, double nugget);
RcppExport SEXP _CBKMR_rnngp_loglik_tauonly_use_AD(SEXP xSEXP, SEXP coordsSEXP, SEXP wSEXP, SEXP tauSEXP, SEXP neighbor_matrixSEXP, SEXP nuggetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type neighbor_matrix(neighbor_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type nugget(nuggetSEXP);
    rcpp_result_gen = Rcpp::wrap(rnngp_loglik_tauonly_use_AD(x, coords, w, tau, neighbor_matrix, nugget));
    return rcpp_result_gen;
END_RCPP
}
// kernel_mat_RBF_rcpp_openmp
arma::mat kernel_mat_RBF_rcpp_openmp(const arma::mat& Z, const arma::vec& w);
RcppExport SEXP _CBKMR_kernel_mat_RBF_rcpp_openmp(SEXP ZSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_mat_RBF_rcpp_openmp(Z, w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CBKMR_logdmvn_arma", (DL_FUNC) &_CBKMR_logdmvn_arma, 2},
    {"_CBKMR_logdmvn_arma_with_U", (DL_FUNC) &_CBKMR_logdmvn_arma_with_U, 2},
    {"_CBKMR_lCBpdf_bernoulli_no_X", (DL_FUNC) &_CBKMR_lCBpdf_bernoulli_no_X, 3},
    {"_CBKMR_build_AD_rcpp", (DL_FUNC) &_CBKMR_build_AD_rcpp, 4},
    {"_CBKMR_rnngp_loglik_tauonly", (DL_FUNC) &_CBKMR_rnngp_loglik_tauonly, 6},
    {"_CBKMR_rnngp_loglik_tauonly_use_AD", (DL_FUNC) &_CBKMR_rnngp_loglik_tauonly_use_AD, 6},
    {"_CBKMR_kernel_mat_RBF_rcpp_openmp", (DL_FUNC) &_CBKMR_kernel_mat_RBF_rcpp_openmp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_CBKMR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
